export const manifest = {
  screens: {
    scr_f3c5n8: {
      name: "Login",
      route: "/login",
      position: { x: 160, y: 2200 },
    },
    scr_n7dp7v: {
      name: "Student Dashboard",
      route: "/",
      state: { role: "student" },
      position: { x: 160, y: 4180 },
    },
    scr_o6umya: {
      name: "Student Courses",
      route: "/courses",
      state: { role: "student" },
      position: { x: 1560, y: 4180 },
    },
    scr_ke43z6: {
      name: "Student Assignments",
      route: "/assignments",
      state: { role: "student" },
      position: { x: 2960, y: 4180 },
    },
    scr_ro085a: {
      name: "Student Calendar",
      route: "/calendar",
      state: { role: "student" },
      position: { x: 4360, y: 4180 },
    },
    scr_pu7e3i: {
      name: "Student Grades",
      route: "/grades",
      state: { role: "student" },
      position: { x: 5760, y: 4180 },
    },
    scr_tx6vaa: {
      name: "Messages",
      route: "/messages",
      state: { role: "student" },
      position: { x: 7160, y: 4180 },
    },
    scr_v7rcbv: {
      name: "Lecturer Dashboard",
      route: "/lecturer",
      state: { role: "lecturer" },
      position: { x: 160, y: 6160 },
    },
    scr_bb5tul: {
      name: "Lecturer Courses",
      route: "/lecturer/courses",
      state: { role: "lecturer" },
      position: { x: 1560, y: 6160 },
    },
    scr_iur0h0: {
      name: "Lecturer Grading",
      route: "/lecturer/grading",
      state: { role: "lecturer" },
      position: { x: 2960, y: 6160 },
    },
    scr_mfcbd3: {
      name: "Lecturer Students",
      route: "/lecturer/students",
      state: { role: "lecturer" },
      position: { x: 4360, y: 6160 },
    },
    scr_whh6ek: {
      name: "Admin Overview",
      route: "/admin",
      state: { role: "admin" },
      position: { x: 160, y: 8140 },
    },
    scr_rrbs8y: {
      name: "Admin Users",
      route: "/admin/users",
      state: { role: "admin" },
      position: { x: 1560, y: 8140 },
    },
    scr_f3c643: {
      name: "Admin Courses",
      route: "/admin/courses",
      state: { role: "admin" },
      position: { x: 2960, y: 8140 },
    },
    scr_6vnu3d: {
      name: "Admin Announcements",
      route: "/admin/announcements",
      state: { role: "admin" },
      position: { x: 4360, y: 8140 },
    },
    scr_0uwc33: {
      name: "Admin Analytics",
      route: "/admin/analytics",
      state: { role: "admin" },
      position: { x: 5760, y: 8140 },
    },
  },
  sections: {
    sec_y8fsdv: {
      name: "Core Dashboard",
      x: 0,
      y: 0,
      width: 8520,
      height: 1180,
    },
    sec_dn2krx: {
      name: "Authentication",
      x: 0,
      y: 1980,
      width: 1520,
      height: 1180,
    },
    sec_pubn1g: {
      name: "Student Dashboard",
      x: 0,
      y: 3960,
      width: 8520,
      height: 1180,
    },
    sec_4vt8vd: {
      name: "Lecturer Dashboard",
      x: 0,
      y: 5940,
      width: 5720,
      height: 1180,
    },
    sec_gg5axj: {
      name: "Admin Dashboard",
      x: 0,
      y: 7920,
      width: 7120,
      height: 1180,
    },
  },
  layers: [
    { kind: "section", id: "sec_y8fsdv", children: [] },
    {
      kind: "section",
      id: "sec_dn2krx",
      children: [{ kind: "screen", id: "scr_f3c5n8" }],
    },
    {
      kind: "section",
      id: "sec_pubn1g",
      children: [
        { kind: "screen", id: "scr_n7dp7v" },
        { kind: "screen", id: "scr_o6umya" },
        { kind: "screen", id: "scr_ke43z6" },
        { kind: "screen", id: "scr_ro085a" },
        { kind: "screen", id: "scr_pu7e3i" },
        { kind: "screen", id: "scr_tx6vaa" },
      ],
    },
    {
      kind: "section",
      id: "sec_4vt8vd",
      children: [
        { kind: "screen", id: "scr_v7rcbv" },
        { kind: "screen", id: "scr_bb5tul" },
        { kind: "screen", id: "scr_iur0h0" },
        { kind: "screen", id: "scr_mfcbd3" },
      ],
    },
    {
      kind: "section",
      id: "sec_gg5axj",
      children: [
        { kind: "screen", id: "scr_whh6ek" },
        { kind: "screen", id: "scr_rrbs8y" },
        { kind: "screen", id: "scr_f3c643" },
        { kind: "screen", id: "scr_6vnu3d" },
        { kind: "screen", id: "scr_0uwc33" },
      ],
    },
  ],
};
